/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/chocolate/chocolateTheme.ts
 * Command: astryx theme build src/themes/chocolate/chocolateTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import { chocolateIconRegistry } from './icons';
/**
 * chocolate theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { chocolateTheme } from './chocolate';
 *   import './chocolate.css';
 */
export const chocolateTheme = {
  name: 'chocolate',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.75rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.0625rem",
    "--font-size-xl": "1.25rem",
    "--font-size-2xl": "1.5rem",
    "--font-size-3xl": "1.8125rem",
    "--font-size-4xl": "2.1875rem",
    "--font-size-5xl": "2.625rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.3333",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.4",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.4118",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.6667",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4118",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.6667",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2381",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2571",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.3793",
    "--duration-fast-min": "95ms",
    "--duration-fast": "125ms",
    "--duration-fast-max": "165ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "525ms",
    "--duration-slow": "700ms",
    "--duration-slow-max": "935ms",
    "--font-family-body": "\"Albert Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "Fraunces, Georgia, \"Times New Roman\", Times, serif",
    "--font-family-code": "\"JetBrains Mono\", \"SF Mono\", Monaco, Consolas, monospace",
    "--color-syntax-keyword": "light-dark(#8C5927, #d4a06a)",
    "--color-syntax-string": "light-dark(#2e6b4a, #7bc49e)",
    "--color-syntax-comment": "light-dark(#B88859, #B88859)",
    "--color-syntax-number": "light-dark(#a06018, #d4b870)",
    "--color-syntax-function": "light-dark(#3a5e8c, #7ba8d4)",
    "--color-syntax-type": "light-dark(#6b4a8c, #b08ed4)",
    "--color-syntax-variable": "light-dark(#4a3520, #EDE4D4)",
    "--color-syntax-operator": "light-dark(#B88859, #c4a882)",
    "--color-syntax-constant": "light-dark(#a06018, #d4b870)",
    "--color-syntax-tag": "light-dark(#8c3a3a, #d47a7a)",
    "--color-syntax-attribute": "light-dark(#8C5927, #d4a06a)",
    "--color-syntax-property": "light-dark(#3a7c6b, #70c4b0)",
    "--color-syntax-punctuation": "light-dark(#9e622e, #cb884d)",
    "--color-syntax-background": "light-dark(#FFFCF7, #1c1610)",
    "--color-accent": "light-dark(#8C5927, #d4a06a)",
    "--color-accent-muted": "light-dark(#8C592714, #d4a06a20)",
    "--color-neutral": "light-dark(#8C59270F, #EDE4D41A)",
    "--color-background-surface": "light-dark(#FFFCF7, #1c1610)",
    "--color-background-body": "light-dark(#FFFCF7, #141010)",
    "--color-overlay": "light-dark(#4a352080, #140e0aCC)",
    "--color-overlay-hover": "light-dark(#4a35200D, #EDE4D40D)",
    "--color-overlay-pressed": "light-dark(#4a35201A, #EDE4D41A)",
    "--color-background-muted": "light-dark(#EDE4D4, #2a2018)",
    "--color-text-primary": "light-dark(#4a3520, #EDE4D4)",
    "--color-text-secondary": "light-dark(#B88859, #c4a882)",
    "--color-text-disabled": "light-dark(#C4AC95, #6b5540)",
    "--color-text-accent": "light-dark(#8C5927, #d4a06a)",
    "--color-on-dark": "#FFFCF7",
    "--color-on-light": "#4a3520",
    "--color-on-accent": "light-dark(#FFFFFF, #4a3520)",
    "--color-on-success": "light-dark(#FFFFFF, #4a3520)",
    "--color-on-error": "light-dark(#FFFFFF, #4a3520)",
    "--color-on-warning": "light-dark(#4a3520, #4a3520)",
    "--color-icon-accent": "light-dark(#8C5927, #d4a06a)",
    "--color-icon-primary": "light-dark(#4a3520, #EDE4D4)",
    "--color-icon-secondary": "light-dark(#B88859, #c4a882)",
    "--color-icon-disabled": "light-dark(#C4AC95, #6b5540)",
    "--color-background-card": "light-dark(#EDE4D4, #2a2018)",
    "--color-background-popover": "light-dark(#FFFCF7, #2a2018)",
    "--color-background-inverted": "light-dark(#4a3520, #EDE4D4)",
    "--color-success": "light-dark(#709900, #96bf2a)",
    "--color-success-muted": "light-dark(#70990020, #96bf2a20)",
    "--color-error": "light-dark(#FD0000, #ff5c5c)",
    "--color-error-muted": "light-dark(#FD000020, #ff5c5c20)",
    "--color-warning": "light-dark(#FFB600, #ffc940)",
    "--color-warning-muted": "light-dark(#FFB60020, #ffc94020)",
    "--color-border": "light-dark(#C4AC95, #EDE4D41A)",
    "--color-border-emphasized": "light-dark(#B88859, #6b5540)",
    "--color-skeleton": "light-dark(#C4AC95, #6b5540)",
    "--color-shadow": "light-dark(#4a35201A, #0000004D)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-blue": "light-dark(#3a5e8c33, #3a5e8c33)",
    "--color-border-blue": "light-dark(#3a5e8c, #7ba8d4)",
    "--color-icon-blue": "light-dark(#3a5e8c, #7ba8d4)",
    "--color-text-blue": "light-dark(#2e4a6e, #8dbce0)",
    "--color-background-cyan": "light-dark(#3a7c7c33, #3a7c7c33)",
    "--color-border-cyan": "light-dark(#3a7c7c, #70c4c4)",
    "--color-icon-cyan": "light-dark(#3a7c7c, #70c4c4)",
    "--color-text-cyan": "light-dark(#2e6060, #82d4d4)",
    "--color-background-gray": "light-dark(#B8885933, #6b554033)",
    "--color-border-gray": "light-dark(#B88859, #B88859)",
    "--color-icon-gray": "light-dark(#B88859, #c4a882)",
    "--color-text-gray": "light-dark(#4a3520, #EDE4D4)",
    "--color-background-green": "light-dark(#70990033, #96bf2a33)",
    "--color-border-green": "light-dark(#709900, #96bf2a)",
    "--color-icon-green": "light-dark(#709900, #96bf2a)",
    "--color-text-green": "light-dark(#5a7a00, #a8d43a)",
    "--color-background-orange": "light-dark(#c4762033, #d4903a33)",
    "--color-border-orange": "light-dark(#c47620, #d4903a)",
    "--color-icon-orange": "light-dark(#c47620, #d4903a)",
    "--color-text-orange": "light-dark(#a06018, #e0a04a)",
    "--color-background-pink": "light-dark(#c44a7033, #e07a9a33)",
    "--color-border-pink": "light-dark(#c44a70, #e07a9a)",
    "--color-icon-pink": "light-dark(#c44a70, #e07a9a)",
    "--color-text-pink": "light-dark(#a03a5a, #f08aaa)",
    "--color-background-purple": "light-dark(#6b4a8c33, #b08ed433)",
    "--color-border-purple": "light-dark(#6b4a8c, #b08ed4)",
    "--color-icon-purple": "light-dark(#6b4a8c, #b08ed4)",
    "--color-text-purple": "light-dark(#553a70, #c0a0e0)",
    "--color-background-red": "light-dark(#FD000033, #ff5c5c33)",
    "--color-border-red": "light-dark(#FD0000, #ff5c5c)",
    "--color-icon-red": "light-dark(#FD0000, #ff5c5c)",
    "--color-text-red": "light-dark(#cc0000, #ff7a7a)",
    "--color-background-teal": "light-dark(#2e6b5a33, #5ab89833)",
    "--color-border-teal": "light-dark(#2e6b5a, #5ab898)",
    "--color-icon-teal": "light-dark(#2e6b5a, #5ab898)",
    "--color-text-teal": "light-dark(#245546, #6ccaaa)",
    "--color-background-yellow": "light-dark(#FFB60033, #ffc94033)",
    "--color-border-yellow": "light-dark(#FFB600, #ffc940)",
    "--color-icon-yellow": "light-dark(#FFB600, #ffc940)",
    "--color-text-yellow": "light-dark(#cc9200, #ffd960)",
    "--radius-none": "0px",
    "--radius-inner": "0.375rem",
    "--radius-element": "0.625rem",
    "--radius-container": "0.75rem",
    "--radius-page": "1.5rem",
    "--radius-full": "9999px",
    "--shadow-low": "0 2px 4px #4a35200D, 0 4px 8px #4a35201A",
    "--shadow-med": "0 2px 4px #4a35200D, 0 4px 12px #4a35201A",
    "--shadow-high": "0 4px 6px #4a35201A, 0 12px 24px #4a352026",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px #8C592730",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #8C592750",
    "--shadow-inset-success": "inset 0px 0px 0px 2px #70990050",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px #FFB60050",
    "--shadow-inset-error": "inset 0px 0px 0px 2px #FD000050"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-full)"
      },
      "variant:secondary": {
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "var(--color-border-emphasized)"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  icons: chocolateIconRegistry,
};

export { chocolateIconRegistry };
