/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/chocolate/chocolateTheme.ts
 * Command: astryx theme build src/themes/chocolate/chocolateTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

import { chocolateIconRegistry } from './icons';
/**
 * chocolate theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { chocolateTheme } from './chocolate';
 *   import './chocolate.css';
 */
export const chocolateTheme = {
  name: 'chocolate',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.75rem",
    "--font-size-base": "0.875rem",
    "--font-size-lg": "1.0625rem",
    "--font-size-xl": "1.25rem",
    "--font-size-2xl": "1.5rem",
    "--font-size-3xl": "1.8125rem",
    "--font-size-4xl": "2.1875rem",
    "--font-size-5xl": "2.625rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.3333",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.4",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.4118",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.4286",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.6667",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.4286",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4118",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.4286",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.4286",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.6667",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2381",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2571",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.3793",
    "--duration-fast-min": "95ms",
    "--duration-fast": "125ms",
    "--duration-fast-max": "165ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "525ms",
    "--duration-slow": "700ms",
    "--duration-slow-max": "935ms",
    "--font-family-body": "var(--font-albert-sans), -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "var(--font-fraunces), Georgia, \"Times New Roman\", Times, serif",
    "--font-family-code": "var(--font-jetbrains-mono), \"SF Mono\", Monaco, Consolas, monospace",
    "--color-syntax-keyword": "light-dark(#006e64, #25d4c2)",
    "--color-syntax-string": "light-dark(#276749, #8acda3)",
    "--color-syntax-comment": "light-dark(#6b5b51, #b9a394)",
    "--color-syntax-number": "light-dark(#805300, #e8bd67)",
    "--color-syntax-function": "light-dark(#625085, #dad4ef)",
    "--color-syntax-type": "light-dark(#625085, #dad4ef)",
    "--color-syntax-variable": "light-dark(#111111, #d4c5c7)",
    "--color-syntax-operator": "light-dark(#6b5b51, #b9a394)",
    "--color-syntax-constant": "light-dark(#805300, #e8bd67)",
    "--color-syntax-tag": "light-dark(#b13f4b, #ee939c)",
    "--color-syntax-attribute": "light-dark(#006e64, #25d4c2)",
    "--color-syntax-property": "light-dark(#006e64, #25d4c2)",
    "--color-syntax-punctuation": "light-dark(#6b5b51, #b9a394)",
    "--color-syntax-background": "light-dark(#fffaf7, #1c1918)",
    "--focus-outline-color": "var(--color-text-accent)",
    "--color-accent": "light-dark(#25d4c2, #25d4c2)",
    "--color-accent-muted": "light-dark(#d5f4ef, #18322e)",
    "--color-neutral": "light-dark(#e8dfd9, #302926)",
    "--color-background-surface": "light-dark(#fffaf7, #1c1918)",
    "--color-background-body": "light-dark(#f7f2ee, #111111)",
    "--color-overlay": "light-dark(#11111180, #111111cc)",
    "--color-overlay-hover": "light-dark(#1111110d, #d4c5c70d)",
    "--color-overlay-pressed": "light-dark(#1111111a, #d4c5c71a)",
    "--color-background-muted": "light-dark(#eee5df, #302926)",
    "--color-text-primary": "light-dark(#111111, #d4c5c7)",
    "--color-text-secondary": "light-dark(#6b5b51, #b9a394)",
    "--color-text-disabled": "light-dark(#97877c, #82736a)",
    "--color-text-accent": "light-dark(#006e64, #25d4c2)",
    "--color-on-dark": "#f7f2ee",
    "--color-on-light": "#111111",
    "--color-on-accent": "#111111",
    "--color-on-success": "light-dark(#ffffff, #111111)",
    "--color-on-error": "light-dark(#ffffff, #111111)",
    "--color-on-warning": "light-dark(#ffffff, #111111)",
    "--color-icon-accent": "light-dark(#006e64, #25d4c2)",
    "--color-icon-primary": "light-dark(#111111, #d4c5c7)",
    "--color-icon-secondary": "light-dark(#6b5b51, #b9a394)",
    "--color-icon-disabled": "light-dark(#97877c, #82736a)",
    "--color-background-card": "light-dark(#fffaf7, #241f1c)",
    "--color-background-popover": "light-dark(#fffaf7, #241f1c)",
    "--color-background-inverted": "light-dark(#111111, #d4c5c7)",
    "--color-success": "light-dark(#276749, #8acda3)",
    "--color-success-muted": "light-dark(#e1eee4, #24372b)",
    "--color-error": "light-dark(#b13f4b, #ee939c)",
    "--color-error-muted": "light-dark(#f8e5e6, #3b2428)",
    "--color-warning": "light-dark(#805300, #e8bd67)",
    "--color-warning-muted": "light-dark(#f5e9d0, #3b3020)",
    "--color-border": "light-dark(#d4c5c7, #51443d)",
    "--color-border-emphasized": "light-dark(#8b776a, #9c8778)",
    "--color-skeleton": "light-dark(#d4c5c7, #51443d)",
    "--color-shadow": "light-dark(#1111111a, #0000004d)",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-blue": "light-dark(#e2e9f3, #243044)",
    "--color-border-blue": "light-dark(#355b85, #a8c7ee)",
    "--color-icon-blue": "light-dark(#355b85, #a8c7ee)",
    "--color-text-blue": "light-dark(#355b85, #a8c7ee)",
    "--color-background-cyan": "light-dark(#d5f0f0, #203333)",
    "--color-border-cyan": "light-dark(#006a70, #91d6dc)",
    "--color-icon-cyan": "light-dark(#006a70, #91d6dc)",
    "--color-text-cyan": "light-dark(#006a70, #91d6dc)",
    "--color-background-gray": "light-dark(#eee5df, #302926)",
    "--color-border-gray": "light-dark(#6b5b51, #b9a394)",
    "--color-icon-gray": "light-dark(#6b5b51, #b9a394)",
    "--color-text-gray": "light-dark(#6b5b51, #b9a394)",
    "--color-background-green": "light-dark(#e1eee4, #24372b)",
    "--color-border-green": "light-dark(#276749, #8acda3)",
    "--color-icon-green": "light-dark(#276749, #8acda3)",
    "--color-text-green": "light-dark(#276749, #8acda3)",
    "--color-background-orange": "light-dark(#f4e6d9, #3b2c20)",
    "--color-border-orange": "light-dark(#8a4d19, #e4b080)",
    "--color-icon-orange": "light-dark(#8a4d19, #e4b080)",
    "--color-text-orange": "light-dark(#8a4d19, #e4b080)",
    "--color-background-pink": "light-dark(#f5e2ea, #382630)",
    "--color-border-pink": "light-dark(#923e68, #e4a4c1)",
    "--color-icon-pink": "light-dark(#923e68, #e4a4c1)",
    "--color-text-pink": "light-dark(#923e68, #e4a4c1)",
    "--color-background-purple": "light-dark(#dad4ef, #30293f)",
    "--color-border-purple": "light-dark(#625085, #dad4ef)",
    "--color-icon-purple": "light-dark(#625085, #dad4ef)",
    "--color-text-purple": "light-dark(#625085, #dad4ef)",
    "--color-background-red": "light-dark(#f8e5e6, #3b2428)",
    "--color-border-red": "light-dark(#b13f4b, #ee939c)",
    "--color-icon-red": "light-dark(#b13f4b, #ee939c)",
    "--color-text-red": "light-dark(#b13f4b, #ee939c)",
    "--color-background-teal": "light-dark(#d5f4ef, #18322e)",
    "--color-border-teal": "light-dark(#006e64, #25d4c2)",
    "--color-icon-teal": "light-dark(#006e64, #25d4c2)",
    "--color-text-teal": "light-dark(#006e64, #25d4c2)",
    "--color-background-yellow": "light-dark(#f5e9d0, #3b3020)",
    "--color-border-yellow": "light-dark(#805300, #e8bd67)",
    "--color-icon-yellow": "light-dark(#805300, #e8bd67)",
    "--color-text-yellow": "light-dark(#805300, #e8bd67)",
    "--radius-none": "0px",
    "--radius-inner": "0.375rem",
    "--radius-element": "0.625rem",
    "--radius-container": "0.75rem",
    "--radius-page": "1.5rem",
    "--radius-full": "9999px",
    "--shadow-low": "0 2px 4px #4a35200D, 0 4px 8px #4a35201A",
    "--shadow-med": "0 2px 4px #4a35200D, 0 4px 12px #4a35201A",
    "--shadow-high": "0 4px 6px #4a35201A, 0 12px 24px #4a352026",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px var(--color-text-accent)",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px var(--color-text-accent)",
    "--shadow-inset-success": "inset 0px 0px 0px 2px var(--color-success)",
    "--shadow-inset-warning": "inset 0px 0px 0px 2px var(--color-warning)",
    "--shadow-inset-error": "inset 0px 0px 0px 2px var(--color-error)"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "var(--radius-full)"
      },
      "variant:secondary": {
        "borderWidth": "1px",
        "borderStyle": "solid",
        "borderColor": "var(--color-border-emphasized)"
      }
    },
    "card": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  icons: chocolateIconRegistry,
};

export { chocolateIconRegistry };
