allowBuilds:
  '@astryxdesign/cli': set this to true or false
  '@astryxdesign/core': set this to true or false
  '@prisma/engines': true
  core-js: true
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - posthog-js@1.418.12
