/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/stone/stoneTheme.ts
 * Command: astryx theme build src/themes/stone/stoneTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/// <reference path="./stone.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const stoneIconRegistry: IconRegistry;
export declare const stoneTheme: DefinedTheme;
