/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/stone/stoneTheme.ts
 * Command: astryx theme build src/themes/stone/stoneTheme.ts
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/ProgressBar' {
  interface ProgressBarVariantMap {
    'accent': true;
    'success': true;
    'warning': true;
    'error': true;
  }
}
